# 01.07 - Tensors

## Introduction: Understanding Tensors in PyTorch

In this Jupyter Notebook, we aim to understand the concept of tensors in PyTorch. PyTorch is a popular library for deep learning. At its core, PyTorch provides a few key features:

1. **Working with `torch.empty()`** - This function is used to create an uninitialized tensor. We will explore its usage and properties.
2. **Utilizing `torch.rand()`** - This function generates a tensor with random numbers. We will take a look at how it can be used within our programs.
3. **Exploring `torch.zeros()`** - This function is used to create a tensor filled with zeros. We will investigate its purposes and applications.
4. **Understanding `torch.ones()`** - This function is used to create a tensor filled with ones. We will delve into its uses and benefits.
5. **The `torch.tensor()` Function** - We will study this function which is used to create a tensor from data.
6. **An In-depth Look at Torch Data Types** - We will delve into different data types available in PyTorch and how to use them.
7. **Mathematical Operations in PyTorch** - We will explore various mathematical operations that can be performed on tensors such as addition, subtraction, multiplication, and division.
8. **The `.item()` Function** - We will learn about this function which is used to get a Python number from a tensor.
9. **Using the `.view` Function** - We will understand this function which is used to reshape a tensor.
10. **Understanding the `.size` Function** - This function returns the size of the tensor. We will explore its usage.
11. **The `.from_numpy()` Function** - We will learn how to create a tensor from a numpy array using this function.
12. **Working with `torch.device()`** - We will study this function which is used to move tensors to and from GPU.
13. **The `.to()` Function** - This function is used to move a tensor to a different device.

By understanding these functions and operations, you will be able to work with tensors effectively in PyTorch.

## Section 1: Working with `torch.empty()`

The `torch.empty()` function in PyTorch is used to create an uninitialized tensor. This means that the function will return a tensor that contains whatever values were in the allocated memory at the time of creation.

Here are some examples of working with `torch.empty()` in PyTorch:

**Example 1: Defining an empty tensor**

In [1]:
import torch

x = torch.empty(1)
print(x)

tensor([0.])


**Example 2: Defining a 2-dimensional empty tensor**

In [2]:
import torch

x = torch.empty(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


**Example 3: Defining a 3-dimensional empty tensor**

In [3]:
import torch

x = torch.empty(2, 2, 2)
print(x)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


**Example 4: Defining a 4-dimensional empty tensor**

In [4]:
import torch

x = torch.empty(2, 2, 2, 2)
print(x)

tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]])


**Example 5: Defining a 5-dimensional empty tensor**

In [5]:
import torch

x = torch.empty(2, 2, 2, 2, 2)
print(x)

tensor([[[[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]]],



        [[[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]]]])


## Section 2: Utilizing `torch.rand()`

The `torch.rand()` function in PyTorch generates a tensor filled with random numbers from a uniform distribution on the interval [0, 1).

Here are some examples of working with `torch.rand()` in PyTorch:

**Example 1: Defining a random tensor**

In [6]:
import torch

x = torch.rand(1)
print(x)

tensor([0.4949])


**Example 2: Defining a 2-dimensional random tensor**

In [7]:
import torch

x = torch.rand(2, 3)
print(x)

tensor([[0.6795, 0.1752, 0.0473],
        [0.2234, 0.8689, 0.5123]])


**Example 3: Defining a 3-dimensional random tensor**

In [8]:
import torch

x = torch.rand(2, 2, 2)
print(x)

tensor([[[0.9409, 0.7853],
         [0.4033, 0.2585]],

        [[0.2676, 0.5262],
         [0.1371, 0.0165]]])


**Example 4: Defining a 4-dimensional random tensor**

In [9]:
import torch

x = torch.rand(2, 2, 2, 2)
print(x)

tensor([[[[0.7902, 0.1909],
          [0.4772, 0.4181]],

         [[0.6422, 0.5291],
          [0.0849, 0.7319]]],


        [[[0.8159, 0.5202],
          [0.6783, 0.8464]],

         [[0.5229, 0.0664],
          [0.2413, 0.2126]]]])


**Example 5: Defining a 5-dimensional random tensor**

In [10]:
import torch

x = torch.rand(2, 2, 2, 2, 2)
print(x)

tensor([[[[[0.5577, 0.5397],
           [0.2806, 0.8878]],

          [[0.8044, 0.7802],
           [0.9322, 0.8498]]],


         [[[0.1611, 0.0366],
           [0.3208, 0.8097]],

          [[0.7798, 0.0721],
           [0.9953, 0.1466]]]],



        [[[[0.8007, 0.7848],
           [0.2358, 0.9521]],

          [[0.8366, 0.8782],
           [0.5403, 0.6339]]],


         [[[0.4441, 0.3820],
           [0.6369, 0.2910]],

          [[0.5550, 0.1248],
           [0.0537, 0.1633]]]]])


**Note:** The `torch.rand()` function generates random numbers from a uniform distribution, meaning each number in the specified range has an equal chance of being selected.

## Section 3: Exploring `torch.zeros()`

The `torch.zeros()` function in PyTorch is used to create a tensor filled with the scalar value 0, with the shape defined by the variable argument size.

Here are some examples of working with `torch.zeros()` in PyTorch:

**Example 1: Defining a zero tensor**

In [11]:
import torch

x = torch.zeros(1)
print(x)

tensor([0.])


**Example 2: Defining a 2-dimensional zero tensor**

In [12]:
import torch

x = torch.zeros(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


**Example 3: Defining a 3-dimensional zero tensor**

In [13]:
import torch

x = torch.zeros(2, 2, 2)
print(x)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


**Example 4: Defining a 4-dimensional zero tensor**

In [14]:
import torch

x = torch.zeros(2, 2, 2, 2)
print(x)

tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]])


**Example 5: Defining a 5-dimensional zero tensor**

In [15]:
import torch

x = torch.zeros(2, 2, 2, 2, 2)
print(x)

tensor([[[[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]]],



        [[[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]]]])


**Note:** The `torch.zeros()` function generates a tensor filled with zeros. This can be particularly useful when you need to initialize a tensor with zeros before using it in computations.

## Section 4: Understanding `torch.ones()`

The `torch.ones()` function in PyTorch is used to create a tensor filled with the scalar value 1, with the shape defined by the variable argument size.

Here are some examples of working with `torch.ones()` in PyTorch:

**Example 1: Defining a ones tensor**

In [16]:
import torch

x = torch.ones(1)
print(x)

tensor([1.])


**Example 2: Defining a 2-dimensional ones tensor**

In [17]:
import torch

x = torch.ones(2, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


**Example 3: Defining a 3-dimensional ones tensor**

In [18]:
import torch

x = torch.ones(2, 2, 2)
print(x)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])


**Example 4: Defining a 4-dimensional ones tensor**

In [19]:
import torch

x = torch.ones(2, 2, 2, 2)
print(x)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])


**Example 5: Defining a 5-dimensional ones tensor**

In [20]:
import torch

x = torch.ones(2, 2, 2, 2, 2)
print(x)

tensor([[[[[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]]],


         [[[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]]]],



        [[[[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]]],


         [[[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]]]]])


**Note:** The `torch.ones()` function generates a tensor filled with ones. This can be particularly useful when you need to initialize a tensor with ones before using it in computations.

## Section 5: The `torch.tensor()` Function

The `torch.tensor()` function in PyTorch is used to create a tensor from data. The data can be a list or an array of numbers.

Here are some examples of working with `torch.tensor()` in PyTorch:

**Example 1: Defining a tensor from a list**

In [21]:
import torch

x = torch.tensor([1, 2, 3, 4, 5])
print(x)

tensor([1, 2, 3, 4, 5])


**Example 2: Defining a tensor from a 2-dimensional list**

In [22]:
import torch

x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


**Example 3: Defining a tensor from a NumPy array**

In [23]:
import torch
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = torch.tensor(arr)
print(x)

tensor([1, 2, 3, 4, 5])


**Example 4: Defining a tensor with specified data types**

In [24]:
import torch

x = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)
print(x)

tensor([1., 2., 3., 4., 5.])


**Example 5: Defining a tensor with specified device**

```python
import torch

x = torch.tensor([1, 2, 3, 4, 5], device='cuda')
print(x)

```

**Note:** The `torch.tensor()` function infers the data type from the data. You can explicitly specify the data type using the `dtype` attribute. You can also specify the device (CPU or GPU) on which the tensor is to be stored using the `device` attribute.

## Section 6: Scalars, Vectors, Matrices, and Tensors

In PyTorch, we can work with numbers in the form of scalars, vectors, matrices, and tensors. Here are some examples:

**Example 1: Defining a Scalar**

A scalar is a single number.

In [26]:
import torch

x = torch.tensor(5)
print(x)

tensor(5)


**Example 2: Defining a Vector**

A vector is an array of numbers.

In [27]:
import torch

x = torch.tensor([1, 2, 3, 4, 5])
print(x)

tensor([1, 2, 3, 4, 5])


**Example 3: Defining a Matrix**

A matrix is a 2-dimensional array of numbers.

In [28]:
import torch

x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In PyTorch, a tensor is a general term used for scalars, vectors, and matrices. It can be a 1-dimensional (scalar), 2-dimensional (vector), 3-dimensional (matrix), or higher-dimensional entity.

**Example 4: Defining a 3-dimensional Tensor**

In [29]:
import torch

x = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(x)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


**Example 5: Defining a 4-dimensional Tensor**

In [30]:
import torch

x = torch.tensor([[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], [[[13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24]]]])
print(x)

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6]],

         [[ 7,  8,  9],
          [10, 11, 12]]],


        [[[13, 14, 15],
          [16, 17, 18]],

         [[19, 20, 21],
          [22, 23, 24]]]])


## Section 7: An In-depth Look at Torch Data Types

In PyTorch, we can specify the data type of the tensor by using the `dtype` attribute. PyTorch supports multiple types of data, including:

- Float types: `torch.float32` (or `torch.float`), `torch.float64` (or `torch.double`), and `torch.float16` (or `torch.half`)
- Integer types: `torch.int8`, `torch.int16` (or `torch.short`), `torch.int32` (or `torch.int`), and `torch.int64` (or `torch.long`)
- Boolean type: `torch.bool`

Here are some examples of defining tensors with specific data types:

**Example 1: Defining a float tensor**

In [31]:
import torch

x = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
print(x)
print(x.dtype)  # Output: torch.float32

tensor([1., 2., 3.])
torch.float32


**Example 2: Defining an integer tensor**

In [32]:
import torch

x = torch.tensor([1, 2, 3], dtype=torch.int)
print(x)
print(x.dtype)  # Output: torch.int32

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


**Example 3: Defining a boolean tensor**

In [33]:
import torch

x = torch.tensor([True, False, True], dtype=torch.bool)
print(x)
print(x.dtype)  # Output: torch.bool

tensor([ True, False,  True])
torch.bool


**Example 4: Changing the data type of a tensor**

We can change the data type of a tensor using the `.to()` function.

In [34]:
import torch

x = torch.tensor([1, 2, 3])
print(x.dtype)  # Output: torch.int64

x = x.to(torch.float32)
print(x.dtype)  # Output: torch.float32

torch.int64
torch.float32


**Example 5: Complex tensor**

PyTorch also supports complex tensors. However, many operations are not supported for complex tensors.

In [35]:
import torch

x = torch.tensor([1+2j, 2+3j, 3+4j], dtype=torch.complex64)
print(x)
print(x.dtype)  # Output: torch.complex64

tensor([1.+2.j, 2.+3.j, 3.+4.j])
torch.complex64


**Note:** It is important to choose the correct data type for your tensor, as this can affect the precision and memory usage of your PyTorch program. For example, a `torch.float32` tensor takes up less memory and is faster to process than a `torch.float64` tensor, but it also has less precision. So you might want to use `torch.float32` for neural network weights, but `torch.float64` for scientific computations.

## Section 8: Mathematical Operations in PyTorch

### 8.1 - Addition Operations

Addition operations in PyTorch can be performed using the `+` operator or the `.add()` function.

Here are some examples of addition operations in PyTorch:

**Example 1: Adding two tensors**

In [36]:
import torch

x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

z = x + y
print(z)  # Output: tensor([5, 7, 9])

tensor([5, 7, 9])


**Example 2: Adding a scalar to a tensor**

In [37]:
import torch

x = torch.tensor([1, 2, 3])

z = x + 2
print(z)  # Output: tensor([3, 4, 5])

tensor([3, 4, 5])


**Example 3: Adding two tensors using the .add() function**

In [38]:
import torch

x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

z = torch.add(x, y)
print(z)  # Output: tensor([5, 7, 9])

tensor([5, 7, 9])


**Example 4: Adding two tensors of different shapes (broadcasting)**

In [39]:
import torch

x = torch.tensor([1, 2, 3])
y = torch.tensor([[1], [2], [3]])

z = x + y
print(z)
# Output: tensor([[2, 3, 4],
#                  [3, 4, 5],
#                  [4, 5, 6]])

tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])


**Example 5: Adding a scalar to a tensor using the .add() function and in-place addition**

In [40]:
import torch

x = torch.tensor([1, 2, 3])

x.add_(2)
print(x)  # Output: tensor([3, 4, 5])

tensor([3, 4, 5])


**Note:** The `_` at the end of the function denotes that the operation is performed in-place, modifying the calling tensor directly.

### 8.2 - Subtraction Operations

Subtraction operations in PyTorch can be performed using the `-` operator or the `.sub()` function.

Here are some examples of subtraction operations in PyTorch:

**Example 1: Subtracting two tensors**

In [41]:
import torch

x = torch.tensor([5, 6, 7])
y = torch.tensor([3, 2, 1])

z = x - y
print(z)  # Output: tensor([2, 4, 6])

tensor([2, 4, 6])


**Example 2: Subtracting a scalar from a tensor**

In [42]:
import torch

x = torch.tensor([3, 4, 5])

z = x - 2
print(z)  # Output: tensor([1, 2, 3])

tensor([1, 2, 3])


**Example 3: Subtracting two tensors using the .sub() function**

In [43]:
import torch

x = torch.tensor([5, 6, 7])
y = torch.tensor([3, 2, 1])

z = torch.sub(x, y)
print(z)  # Output: tensor([2, 4, 6])

tensor([2, 4, 6])


**Example 4: Subtracting two tensors of different shapes (broadcasting)**

In [44]:
import torch

x = torch.tensor([5, 6, 7])
y = torch.tensor([[2], [1], [0]])

z = x - y
print(z)
# Output: tensor([[3, 4, 5],
#                  [4, 5, 6],
#                  [5, 6, 7]])

tensor([[3, 4, 5],
        [4, 5, 6],
        [5, 6, 7]])


**Example 5: Subtracting a scalar from a tensor using the .sub() function and in-place subtraction**

In [45]:
import torch

x = torch.tensor([4, 5, 6])

x.sub_(2)
print(x)  # Output: tensor([2, 3, 4])

tensor([2, 3, 4])


**Note:** The `_` at the end of the function denotes that the operation is performed in-place, modifying the calling tensor directly.

### 8.3 - Multiplication Operations

Multiplication operations in PyTorch can be performed using the `*` operator or the `.mul()` function.

Here are some examples of multiplication operations in PyTorch:

**Example 1: Multiplying two tensors**

In [46]:
import torch

x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

z = x * y
print(z)  # Output: tensor([4, 10, 18])

tensor([ 4, 10, 18])


**Example 2: Multiplying a tensor by a scalar**

In [47]:
import torch

x = torch.tensor([1, 2, 3])

z = x * 2
print(z)  # Output: tensor([2, 4, 6])

tensor([2, 4, 6])


**Example 3: Multiplying two tensors using the .mul() function**

In [48]:
import torch

x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

z = torch.mul(x, y)
print(z)  # Output: tensor([4, 10, 18])

tensor([ 4, 10, 18])


**Example 4: Multiplying two tensors of different shapes (broadcasting)**

In [49]:
import torch

x = torch.tensor([1, 2, 3])
y = torch.tensor([[1], [2], [3]])

z = x * y
print(z)
# Output: tensor([[1, 2, 3],
#                  [2, 4, 6],
#                  [3, 6, 9]])

tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])


**Example 5: Multiplying a tensor by a scalar using the .mul() function and in-place multiplication**

In [50]:
import torch

x = torch.tensor([1, 2, 3])

x.mul_(2)
print(x)  # Output: tensor([2, 4, 6])

tensor([2, 4, 6])


**Note:** The `_` at the end of the function denotes that the operation is performed in-place, modifying the calling tensor directly.

### 8.4 - Division Operations

Division operations in PyTorch can be performed using the `/` operator or the `.div()` function.

Here are some examples of division operations in PyTorch:

**Example 1: Dividing two tensors**

In [51]:
import torch

x = torch.tensor([4, 9, 16])
y = torch.tensor([2, 3, 4])

z = x / y
print(z)  # Output: tensor([2., 3., 4.])

tensor([2., 3., 4.])


**Example 2: Dividing a tensor by a scalar**

In [52]:
import torch

x = torch.tensor([2, 4, 6])

z = x / 2
print(z)  # Output: tensor([1., 2., 3.])

tensor([1., 2., 3.])


**Example 3: Dividing two tensors using the .div() function**

In [53]:
import torch

x = torch.tensor([4, 9, 16])
y = torch.tensor([2, 3, 4])

z = torch.div(x, y)
print(z)  # Output: tensor([2., 3., 4.])

tensor([2., 3., 4.])


**Example 4: Dividing two tensors of different shapes (broadcasting)**

In [54]:
import torch

x = torch.tensor([2, 4, 6])
y = torch.tensor([[2], [1], [0.5]])

z = x / y
print(z)
# Output: tensor([[1., 2., 3.],
#                  [2., 4., 6.],
#                  [4., 8., 12.]])

tensor([[ 1.,  2.,  3.],
        [ 2.,  4.,  6.],
        [ 4.,  8., 12.]])


**Example 5: Dividing a tensor by a scalar using the .div() function and in-place division**

In [64]:
import torch

x = torch.tensor([2., 4., 6.])

x.div_(2)
print(x)  # Output: tensor([1., 2., 3.])

tensor([1., 2., 3.])


**Note:** The `_` at the end of the function denotes that the operation is performed in-place, modifying the calling tensor directly.

## Section 9: The `.item()` Function

The `.item()` function in PyTorch is used to obtain a Python number from a tensor containing a single value. It returns the value of this tensor as a standard Python number.

Here are some examples of using the `.item()` function in PyTorch:

**Example 1: Extracting a number from a tensor**

In [65]:
import torch

x = torch.tensor([1])
print(x.item())  # Output: 1

1


**Example 2: Extracting a number from a more complex tensor**

In [66]:
import torch

x = torch.tensor([[2]])
print(x.item())  # Output: 2

2


**Example 3: Extracting a number from a tensor with multiple items**

In this case, trying to extract a number using `.item()` will fail because it only works for tensors with one element.

In [68]:
import torch

x = torch.tensor([1, 2, 3])

# This will throw a RuntimeError: a Tensor with 3 elements cannot be converted to Scalar
print(x.item())

RuntimeError: a Tensor with 3 elements cannot be converted to Scalar

**Example 4: Extracting a number from a tensor with no items**

Similarly, trying to extract a number from a tensor with no elements will also fail.

In [70]:
import torch

x = torch.tensor([])

# This will throw a RuntimeError: a Tensor with 0 elements cannot be converted to Scalar
print(x.item())

RuntimeError: a Tensor with 0 elements cannot be converted to Scalar

**Example 5: Extracting a number after a calculation**

The `.item()` function can be particularly useful to extract a number after a calculation.

In [71]:
import torch

x = torch.tensor([5])
y = torch.tensor([2])

z = (x / y).item()
print(z)  # Output: 2.5

2.5


**Note:** The `.item()` function is used to convert a zero-dimensional tensor to a Python number. If the tensor has more than one element, you will need to use methods such as `.tolist()` to convert the tensor to a Python list.

## Section 10: Using the `.view()` Function

The `.view()` function in PyTorch allows you to reshape a tensor without changing its data.

Here are some examples of using the `.view()` function in PyTorch:

**Example 1: Reshape a 1D tensor to a 2D tensor**

In [72]:
import torch

x = torch.tensor([1, 2, 3, 4, 5, 6])
y = x.view(2, 3)

print(y)
# Output: tensor([[1, 2, 3],
#                  [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])


**Example 2: Reshape a 2D tensor to a 3D tensor**

In [73]:
import torch

x = torch.tensor([[1, 2, 3], [4, 5, 6]])
y = x.view(2, 1, 3)

print(y)
# Output: tensor([[[1, 2, 3]],
#                  [[4, 5, 6]]])

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])


**Example 3: Reshape a 3D tensor to a 2D tensor**

In [74]:
import torch

x = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
y = x.view(4, 2)

print(y)
# Output: tensor([[1, 2],
#                  [3, 4],
#                  [5, 6],
#                  [7, 8]])

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


**Example 4: Use `-1` to infer the size**

You can use `-1` as one of the dimensions in the `.view()` function. PyTorch will automatically infer the correct size for the dimension with `-1`, based on the original tensor's size.

In [75]:
import torch

x = torch.tensor([1, 2, 3, 4, 5, 6])
y = x.view(-1, 2)

print(y)
# Output: tensor([[1, 2],
#                  [3, 4],
#                  [5, 6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]])


**Example 5: Changes in the original tensor reflect in the reshaped tensor**

When you reshape a tensor using `.view()`, the reshaped tensor and the original tensor share the same underlying data. So, changing the original tensor will also change the reshaped tensor.

In [76]:
import torch

x = torch.tensor([1, 2, 3, 4, 5, 6])
y = x.view(2, 3)

x[0] = 10

print(y)
# Output: tensor([[10,  2,  3],
#                  [ 4,  5,  6]])

tensor([[10,  2,  3],
        [ 4,  5,  6]])


**Note:** If you want to create a reshaped tensor that does not share data with the original tensor, you can use the `.clone()` function before calling `.view()`.

## Section 11: Understanding the `.size()` Function

The `.size()` function in PyTorch returns the size of a tensor. It is a property of the tensor object and returns a torch.Size object, which is a tuple.

Here are some examples of using the `.size()` function in PyTorch:

**Example 1: Getting the Size of a Tensor**

In [77]:
import torch

x = torch.tensor([1, 2, 3])
print(x.size())  # Output: torch.Size([3])

torch.Size([3])


**Example 2: Getting the Size of a 2D Tensor**

In [78]:
import torch

x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x.size())  # Output: torch.Size([2, 3])

torch.Size([2, 3])


**Example 3: Getting the Size of a 3D Tensor**

In [79]:
import torch

x = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(x.size())  # Output: torch.Size([2, 2, 3])

torch.Size([2, 2, 3])


**Example 4: Getting the Size of a Specific Dimension**

You can pass an integer to the `.size()` function to get the size of a specific dimension.

In [80]:
import torch

x = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(x.size(0))  # Output: 2
print(x.size(1))  # Output: 2
print(x.size(2))  # Output: 3

2
2
3


**Example 5: Using the Size of a Tensor in Computations**

The size of a tensor often comes in handy when writing code that needs to be generalizable to tensors of different sizes.

In [81]:
import torch

x = torch.tensor([1, 2, 3])
y = torch.rand(x.size())

print(y)  # Output: tensor with the same size as x, with random values

tensor([0.9391, 0.9421, 0.2577])


**Note:** The `.size()` function returns a tuple, so it can be used wherever a tuple is expected.

## Section 12: The `.from_numpy()` Function

The `.from_numpy()` function in PyTorch is used to create a tensor from a numpy array. The returned tensor and the numpy array share the same underlying memory. Changes to the numpy array will be reflected in the tensor as well, and vice-versa.

Here are some examples of using the `.from_numpy()` function in PyTorch:

**Example 1: Creating a Tensor from a Numpy Array**

In [82]:
import numpy as np
import torch

a = np.array([1, 2, 3])
x = torch.from_numpy(a)

print(x)  # Output: tensor([1, 2, 3])

tensor([1, 2, 3])


**Example 2: Changes in the Numpy Array Reflect in the Tensor**

In [83]:
import numpy as np
import torch

a = np.array([1, 2, 3])
x = torch.from_numpy(a)

a[0] = 10

print(x)  # Output: tensor([10, 2, 3])

tensor([10,  2,  3])


**Example 3: Changes in the Tensor Reflect in the Numpy Array**

In [84]:
import numpy as np
import torch

a = np.array([1, 2, 3])
x = torch.from_numpy(a)

x[0] = 10

print(a)  # Output: array([10, 2, 3])

[10  2  3]


**Example 4: Creating a Tensor from a Multidimensional Numpy Array**

In [85]:
import numpy as np
import torch

a = np.array([[1, 2, 3], [4, 5, 6]])
x = torch.from_numpy(a)

print(x)
# Output: tensor([[1, 2, 3],
#                  [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])


**Example 5: Changes in a Reshaped Tensor Reflect in the Numpy Array**

In [86]:
import numpy as np
import torch

a = np.array([1, 2, 3, 4, 5, 6])
x = torch.from_numpy(a)

y = x.view(2, 3)
y[0, 0] = 10

print(a)  # Output: array([10, 2, 3, 4, 5, 6])

[10  2  3  4  5  6]


**Note:** The `.from_numpy()` function is a useful tool for converting numpy arrays to tensors, especially when we want to perform operations that are easier in PyTorch. However, be aware that the tensor and the numpy array share memory, so changes in one will affect the other.

## Section 13: Working with `torch.device()`

The `torch.device` in PyTorch is a class used to specify the device where a tensor is or will be allocated. This device can be a CPU device or a CUDA device. CUDA is a parallel computing platform and application programming interface model created by Nvidia. It allows software developers to use a CUDA-enabled graphics processing unit for general purpose processing, which can significantly speed up the computation time for large tensors.

You can specify the device at the time of creation of a tensor.

**Example 1: Creating a Tensor on CPU**

In [87]:
import torch

device = torch.device("cpu")
x = torch.tensor([1, 2, 3], device=device)
print(x.device)  # Output: cpu

cpu


**Example 2: Creating a Tensor on GPU (CUDA for Windows/Linux)**

If you have CUDA available, you can create the tensor directly on the GPU.

```python
import torch

device = torch.device("cuda")
x = torch.tensor([1, 2, 3], device=device)
print(x.device)  # Output: cuda:0

```

**Example 3: Moving a Tensor to GPU (CUDA for Windows/Linux)**

You can move an existing tensor from one device to another by using the `.to()` function.

```python
import torch

x = torch.tensor([1, 2, 3])
device = torch.device("cuda")
x = x.to(device)
print(x.device)  # Output: cuda:0

```

**Example 4: Moving a Tensor to CPU**

```python
import torch

device = torch.device("cuda")
x = torch.tensor([1, 2, 3], device=device)
x = x.to("cpu")
print(x.device)  # Output: cpu

```

**Example 5: Setting Device Based on CUDA Availability**

Sometimes, you might write code that is supposed to run on different machines, not all of which have a CUDA device. In such cases, it is useful to check if CUDA is available and then set your device accordingly.

In [88]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
x = torch.tensor([1, 2, 3], device=device)
print(x.device)  # Output: cuda:0 if CUDA is available, otherwise cpu

cpu


**Example 6: Creating a Tensor on MPS (MacOS)**

For MacOS users, CUDA is not available. However, Apple provides Metal Performance Shaders (MPS) that serve a similar purpose. MPS provides a set of high-performance graphics and data-parallel primitives that can significantly enhance an application's performance.

In [89]:
import torch

device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
x = torch.tensor([1, 2, 3], device=device)
print(x.device)  # Output: mps

mps:0


**Example 7: Creating a Tensor on GPU regardless of OS**

In [90]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else \
                      "mps" if torch.backends.mps.is_available() else \
                      "cpu")
x = torch.tensor([1, 2, 3], device=device)
print(x.device)  # Output: cuda:0 if CUDA is available, otherwise mps:0 if MPS is available, otherwise cpu

mps:0


**Note:** When working with GPUs, it's important to note that the tensor computations are performed where the tensor is located (CPU or GPU). Therefore, if you're performing an operation involving two tensors, they need to be on the same device. Otherwise, you'll have to move one tensor to the device where the other tensor resides.

## Section 14: The `.to()` Function

The `.to()` function in PyTorch is used to move a tensor to a different device or convert its datatype. If no argument is provided, the function returns a tensor with the same dtype and the same device as the input tensor.

Here are some examples of using the `.to()` function in PyTorch:

**Example 1: Moving a Tensor to a Different Device**

In [91]:
import torch

x = torch.tensor([1, 2, 3])
device = torch.device("cuda" if torch.cuda.is_available() else \
                      "mps" if torch.backends.mps.is_available() else \
                      "cpu")
x = x.to(device)
print(x.device)

mps:0


**Example 2: Converting a Tensor's Datatype**

In [92]:
import torch

x = torch.tensor([1, 2, 3], dtype=torch.int32)
x = x.to(dtype=torch.float32)
print(x.dtype)  # Output: torch.float32

torch.float32


**Example 3: Moving a Tensor to a Different Device and Changing its Datatype**

In [93]:
import torch

x = torch.tensor([1, 2, 3], dtype=torch.int32)
device = torch.device("cuda" if torch.cuda.is_available() else \
                      "mps" if torch.backends.mps.is_available() else \
                      "cpu")
x = x.to(device, dtype=torch.float32)
print(x.device)  # Output: cuda:0 / mps:0 / cpu
print(x.dtype)  # Output: torch.float32


mps:0
torch.float32


**Example 4: Using `.to()` with Model Parameters**

When dealing with PyTorch models, you can use the `.to()` function to move all model parameters and buffers to a CUDA device at once.

In [94]:
import torch
import torchvision.models as models

model = models.resnet50()
device = torch.device("cuda" if torch.cuda.is_available() else \
                      "mps" if torch.backends.mps.is_available() else \
                      "cpu")
model = model.to(device)

**Example 5: Handling Tensors with Multiple Devices**

In case of multiple CUDA devices, `.to()` function can also change the device of the tensor to a different GPU.

```python
import torch

x = torch.tensor([1, 2, 3], device="cuda:0")
x = x.to("cuda:1")
print(x.device)  # Output: cuda:1

```

**Note:** When moving tensors between devices or changing their datatypes, it's important to ensure that all tensors involved in a computation are on the same device and have the same datatype. Otherwise, PyTorch will raise an error.

## Challenge

Your challenge is to create a `TensorOperations` class in PyTorch that performs basic tensor operations including addition, subtraction, multiplication and division. It should also have methods for moving tensors between CPU and GPU devices.

### Inputs:

- A constructor that takes a tensor and a device type (either "cpu" or "cuda") as inputs.

### Methods:

- An `add` method that takes a scalar value as input and returns a new tensor that is the result of adding the scalar value to the original tensor.
- A `subtract` method that takes a scalar value as input and returns a new tensor that is the result of subtracting the scalar value from the original tensor.
- A `multiply` method that takes a scalar value as input and returns a new tensor that is the result of multiplying the original tensor by the scalar value.
- A `divide` method that takes a scalar value as input and returns a new tensor that is the result of dividing the original tensor by the scalar value.
- A `move` method that takes a device type as input and moves the tensor to the specified device.

### Output Format

- All methods must return a tensor.

### Explanation

Consider the following code:

```python
import torch

# Create a tensor with elements 1, 2, and 3 on the CPU
tensor_op = TensorOperations(torch.tensor([1, 2, 3]), 'cpu')

# Add 2 to the tensor
print(tensor_op.add(2))  # Output: tensor([3, 4, 5])

# Subtract 1 from the tensor
print(tensor_op.subtract(1))  # Output: tensor([0, 1, 2])

# Multiply the tensor by 3
print(tensor_op.multiply(3))  # Output: tensor([3, 6, 9])

# Divide the tensor by 2
print(tensor_op.divide(2))  # Output: tensor([0.5, 1.0, 1.5])

# Move the tensor to GPU if available
print(tensor_op.move('cuda' if torch.cuda.is_available() else 'cpu'))  # Output: tensor([1, 2, 3], device='cuda:0') if CUDA is available, otherwise tensor([1, 2, 3])

```

When the `TensorOperations` class is implemented correctly, this code should output the expected results as shown in the comments.

In [ ]:
### WRITE YOUR CODE BELOW THIS LINE ###


### WRITE YOUR CODE ABOVE THIS LINE ###